language: go

notifications:
  email: false

go:
  - 1.8

before_install:
  - go get -v github.com/golang/dep/cmd/dep

install:
  - $GOPATH/bin/dep ensure -v

before_script:
  - go get -v github.com/mattn/goveralls

script:
  - $GOPATH/bin/goveralls -service=travis-ci
